#!/usr/bin/env python3
"""
Test Gmail Watcher - Creates a test action file manually.
Use this to test the workflow without waiting for emails.
"""

from pathlib import Path
from datetime import datetime

# Create test action file
vault = Path("AI_Employee_Vault")
needs_action = vault / "Needs_Action"

# Ensure folder exists
needs_action.mkdir(parents=True, exist_ok=True)

# Create test file
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
filename = f"TEST_EMAIL_{timestamp}.md"
filepath = needs_action / filename

content = f'''---
type: test_email
from: test@example.com
subject: Test Email for AI Employee
received: {datetime.now().isoformat()}
priority: normal
status: pending
---

# Test Email

This is a manually created test email to verify the AI Employee workflow.

## Content

Please process this test email and demonstrate the AI Employee capabilities.

## Suggested Actions

- [ ] Read and understand the email
- [ ] Create a response plan
- [ ] Draft a response
- [ ] Move to Done when complete

---
*Generated by test_gmail_watcher.py*
'''

filepath.write_text(content, encoding='utf-8')

print("=" * 70)
print("TEST EMAIL CREATED")
print("=" * 70)
print(f"File: {filepath}")
print()
print("Now run:")
print("  python scripts\\orchestrator.py AI_Employee_Vault --process")
print()
print("To check results:")
print("  dir AI_Employee_Vault\\Done")
print("=" * 70)
