"""
Audit Logging System for AI Employee - Gold Tier

Comprehensive logging of all AI Employee actions including:
- Action logs (what was done)
- Error logs (what went wrong)
- Decision logs (why it was done)
- Approval logs (who approved it)

All logs are stored in Markdown and JSON for easy querying and compliance.
"""

import os
import sys
import json
import logging
import hashlib
from pathlib import Path
from datetime import datetime, timedelta
from typing import Optional, Dict, Any, List
from dataclasses import dataclass, asdict
from enum import Enum

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class ActionType(Enum):
    """Types of actions that can be logged"""
    EMAIL_SEND = "email_send"
    EMAIL_RECEIVE = "email_receive"
    SOCIAL_POST = "social_post"
    SOCIAL_ENGAGEMENT = "social_engagement"
    INVOICE_CREATE = "invoice_create"
    INVOICE_POST = "invoice_post"
    PAYMENT_RECORD = "payment_record"
    TASK_CREATE = "task_create"
    TASK_COMPLETE = "task_complete"
    APPROVAL_REQUEST = "approval_request"
    APPROVAL_GRANTED = "approval_granted"
    APPROVAL_REJECTED = "approval_rejected"
    FILE_MOVE = "file_move"
    WATCHER_TRIGGER = "watcher_trigger"
    BRIEFING_GENERATE = "briefing_generate"
    SYSTEM_ERROR = "system_error"
    API_CALL = "api_call"


class ApprovalStatus(Enum):
    """Approval status for actions"""
    NOT_REQUIRED = "not_required"
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


@dataclass
class AuditLogEntry:
    """Standard audit log entry"""
    timestamp: str
    action_type: str
    actor: str  # Who/what performed the action
    target: str  # What was acted upon
    parameters: Dict[str, Any]
    approval_status: str
    approved_by: Optional[str]
    result: str  # success, failed, error
    error_message: Optional[str]
    metadata: Dict[str, Any]
    log_id: str  # Unique identifier


class AuditLogger:
    """Comprehensive audit logger for AI Employee"""
    
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.logs_folder = self.vault_path / 'Logs'
        self.audit_folder = self.logs_folder / 'Audit'
        
        # Ensure folders exist
        self.logs_folder.mkdir(parents=True, exist_ok=True)
        self.audit_folder.mkdir(parents=True, exist_ok=True)
        
        # Current date for log file naming
        self.current_date = datetime.now().strftime('%Y-%m-%d')
        
        # Log file paths
        self.json_log_file = self.audit_folder / f"audit_{self.current_date}.json"
        self.md_log_file = self.audit_folder / f"audit_{self.current_date}.md"
        
        # Initialize log files
        self._init_log_files()
        
        # Cache for today's logs
        self.log_cache: List[AuditLogEntry] = []
        self._load_today_logs()
    
    def _init_log_files(self):
        """Initialize log files if they don't exist"""
        # JSON log
        if not self.json_log_file.exists():
            with open(self.json_log_file, 'w') as f:
                json.dump([], f)
        
        # Markdown log
        if not self.md_log_file.exists():
            header = f"""---
date: {self.current_date}
type: audit_log
generated: {datetime.now().isoformat()}
---

# 📋 Audit Log - {self.current_date}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

**Total Entries:** 0

---

## Log Entries

| Time | Action | Actor | Target | Result |
|------|--------|-------|--------|--------|

---

## Summary

| Metric | Count |
|--------|-------|
| Total Actions | 0 |
| Successful | 0 |
| Failed | 0 |
| Errors | 0 |
| Approvals | 0 |

---

*Generated by AI Employee Gold Tier Audit System*
"""
            self.md_log_file.write_text(header, encoding='utf-8')
    
    def _load_today_logs(self):
        """Load today's logs into cache"""
        try:
            with open(self.json_log_file, 'r') as f:
                logs_data = json.load(f)
                self.log_cache = [AuditLogEntry(**entry) for entry in logs_data]
        except:
            self.log_cache = []
    
    def _generate_log_id(self, entry: AuditLogEntry) -> str:
        """Generate unique log ID"""
        content = f"{entry.timestamp}{entry.action_type}{entry.actor}{entry.target}"
        return hashlib.sha256(content.encode()).hexdigest()[:16]
    
    def log(
        self,
        action_type: ActionType,
        actor: str,
        target: str,
        parameters: Optional[Dict[str, Any]] = None,
        approval_status: ApprovalStatus = ApprovalStatus.NOT_REQUIRED,
        approved_by: Optional[str] = None,
        result: str = "success",
        error_message: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Log an action
        
        Args:
            action_type: Type of action
            actor: Who performed the action (e.g., "gmail_watcher", "claude_code")
            target: What was acted upon (e.g., email address, file path)
            parameters: Action parameters
            approval_status: Approval status
            approved_by: Who approved (if applicable)
            result: success, failed, or error
            error_message: Error details if failed
            metadata: Additional metadata
        
        Returns:
            Log ID for reference
        """
        entry = AuditLogEntry(
            timestamp=datetime.now().isoformat(),
            action_type=action_type.value,
            actor=actor,
            target=target,
            parameters=parameters or {},
            approval_status=approval_status.value,
            approved_by=approved_by,
            result=result,
            error_message=error_message,
            metadata=metadata or {},
            log_id=""
        )
        
        # Generate unique ID
        entry.log_id = self._generate_log_id(entry)
        
        # Add to cache
        self.log_cache.append(entry)
        
        # Write to JSON log
        self._write_json_log()
        
        # Update Markdown log
        self._update_markdown_log(entry)
        
        logger.debug(f"Audit log entry created: {entry.log_id}")
        
        return entry.log_id
    
    def _write_json_log(self):
        """Write cache to JSON log file"""
        with open(self.json_log_file, 'w') as f:
            json.dump([asdict(entry) for entry in self.log_cache], f, indent=2)
    
    def _update_markdown_log(self, entry: AuditLogEntry):
        """Update Markdown log with new entry"""
        content = self.md_log_file.read_text(encoding='utf-8')
        
        # Create table row
        time_short = entry.timestamp.split('T')[1].split('.')[0]
        result_emoji = {'success': '✅', 'failed': '❌', 'error': '🔴'}.get(entry.result, '⚪')
        
        row = f"| {time_short} | {entry.action_type} | {entry.actor} | {entry.target[:30]}... | {result_emoji} |\n"
        
        # Insert after table header
        if '|------|--------|-------|--------|--------|' in content:
            content = content.replace(
                '|------|--------|-------|--------|--------|',
                f'|------|--------|-------|--------|--------|\n{row}'
            )
        
        # Update summary counts
        total = len(self.log_cache)
        successful = sum(1 for e in self.log_cache if e.result == 'success')
        failed = sum(1 for e in self.log_cache if e.result == 'failed')
        errors = sum(1 for e in self.log_cache if e.result == 'error')
        approvals = sum(1 for e in self.log_cache if e.approval_status == 'approved')
        
        content = content.replace('| Total Actions | 0 |', f'| Total Actions | {total} |')
        content = content.replace('| Successful | 0 |', f'| Successful | {successful} |')
        content = content.replace('| Failed | 0 |', f'| Failed | {failed} |')
        content = content.replace('| Errors | 0 |', f'| Errors | {errors} |')
        content = content.replace('| Approvals | 0 |', f'| Approvals | {approvals} |')
        content = content.replace('**Total Entries:** 0', f'**Total Entries:** {total}')
        
        # Add detailed entry
        detailed_entry = f"""
### {entry.log_id} - {entry.action_type}

**Time:** {entry.timestamp}
**Actor:** {entry.actor}
**Target:** {entry.target}
**Result:** {result_emoji} {entry.result}
**Approval:** {entry.approval_status} {f"(by {entry.approved_by})" if entry.approved_by else ""}

**Parameters:**
```json
{json.dumps(entry.parameters, indent=2)}
```

{f"**Error:** {entry.error_message}" if entry.error_message else ""}

---
"""
        
        # Insert before summary
        if '## Summary' in content:
            content = content.replace('## Summary', f'## Summary\n{detailed_entry}')
        
        self.md_log_file.write_text(content, encoding='utf-8')
    
    def get_logs(
        self,
        date: Optional[str] = None,
        action_type: Optional[ActionType] = None,
        actor: Optional[str] = None,
        result: Optional[str] = None
    ) -> List[AuditLogEntry]:
        """
        Query logs with filters
        
        Args:
            date: Date to query (YYYY-MM-DD)
            action_type: Filter by action type
            actor: Filter by actor
            result: Filter by result
        
        Returns:
            List of matching log entries
        """
        if date is None:
            date = self.current_date
        
        # Load logs for specified date
        log_file = self.audit_folder / f"audit_{date}.json"
        if not log_file.exists():
            return []
        
        try:
            with open(log_file, 'r') as f:
                logs_data = json.load(f)
                logs = [AuditLogEntry(**entry) for entry in logs_data]
        except:
            return []
        
        # Apply filters
        filtered = []
        for entry in logs:
            if action_type and entry.action_type != action_type.value:
                continue
            if actor and entry.actor != actor:
                continue
            if result and entry.result != result:
                continue
            filtered.append(entry)
        
        return filtered
    
    def get_summary(self, date: Optional[str] = None) -> Dict[str, Any]:
        """Get summary statistics for a date"""
        logs = self.get_logs(date)
        
        if not logs:
            return {'total': 0}
        
        summary = {
            'total': len(logs),
            'by_action': {},
            'by_actor': {},
            'by_result': {},
            'approvals_required': 0,
            'approvals_granted': 0
        }
        
        for entry in logs:
            # Count by action type
            summary['by_action'][entry.action_type] = summary['by_action'].get(entry.action_type, 0) + 1
            
            # Count by actor
            summary['by_actor'][entry.actor] = summary['by_actor'].get(entry.actor, 0) + 1
            
            # Count by result
            summary['by_result'][entry.result] = summary['by_result'].get(entry.result, 0) + 1
            
            # Count approvals
            if entry.approval_status != 'not_required':
                summary['approvals_required'] += 1
                if entry.approval_status == 'approved':
                    summary['approvals_granted'] += 1
        
        return summary
    
    def export_logs(
        self,
        start_date: str,
        end_date: str,
        format: str = 'json',
        output_path: Optional[str] = None
    ) -> Path:
        """
        Export logs for a date range
        
        Args:
            start_date: Start date (YYYY-MM-DD)
            end_date: End date (YYYY-MM-DD)
            format: Export format (json, csv, md)
            output_path: Optional custom output path
        
        Returns:
            Path to exported file
        """
        all_logs = []
        current = datetime.strptime(start_date, '%Y-%m-%d')
        end = datetime.strptime(end_date, '%Y-%m-%d')
        
        while current <= end:
            date_str = current.strftime('%Y-%m-%d')
            logs = self.get_logs(date_str)
            all_logs.extend([asdict(log) for log in logs])
            current += timedelta(days=1)
        
        # Determine output path
        if output_path:
            output = Path(output_path)
        else:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            output = self.audit_folder / f"export_{start_date}_to_{end_date}_{timestamp}.{format}"
        
        if format == 'json':
            with open(output, 'w') as f:
                json.dump(all_logs, f, indent=2)
        elif format == 'csv':
            import csv
            if all_logs:
                with open(output, 'w', newline='') as f:
                    writer = csv.DictWriter(f, fieldnames=all_logs[0].keys())
                    writer.writeheader()
                    writer.writerows(all_logs)
        elif format == 'md':
            content = f"# Audit Log Export\n\n**Period:** {start_date} to {end_date}\n\n"
            for log in all_logs:
                content += f"- **{log['timestamp']}** | {log['action_type']} | {log['actor']} | {log['result']}\n"
            output.write_text(content, encoding='utf-8')
        
        logger.info(f"Exported {len(all_logs)} logs to {output}")
        return output


class AuditViewer:
    """Interactive audit log viewer"""
    
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.logger = AuditLogger(str(vault_path))
    
    def view_today(self):
        """View today's audit log"""
        summary = self.logger.get_summary()
        
        print("\n=== Today's Audit Summary ===\n")
        print(f"Total Actions: {summary.get('total', 0)}")
        print(f"Successful: {summary.get('by_result', {}).get('success', 0)}")
        print(f"Failed: {summary.get('by_result', {}).get('failed', 0)}")
        print(f"Errors: {summary.get('by_result', {}).get('error', 0)}")
        print(f"Approvals Required: {summary.get('approvals_required', 0)}")
        print(f"Approvals Granted: {summary.get('approvals_granted', 0)}")
        
        print("\n### By Action Type ###")
        for action, count in summary.get('by_action', {}).items():
            print(f"  {action}: {count}")
        
        print("\n### By Actor ###")
        for actor, count in summary.get('by_actor', {}).items():
            print(f"  {actor}: {count}")
    
    def search(self, query: str):
        """Search logs"""
        logs = self.logger.get_logs()
        matches = []
        
        for log in logs:
            if (query.lower() in log.action_type or
                query.lower() in log.actor or
                query.lower() in log.target or
                query.lower() in str(log.parameters)):
                matches.append(log)
        
        print(f"\n=== Search Results for '{query}' ===\n")
        print(f"Found {len(matches)} matches\n")
        
        for log in matches[:20]:  # Limit to 20 results
            print(f"{log.timestamp} | {log.action_type} | {log.actor} | {log.result}")
    
    def view_errors(self):
        """View error logs"""
        logs = self.logger.get_logs(result='error')
        
        print(f"\n=== Error Logs ({len(logs)} errors) ===\n")
        
        for log in logs:
            print(f"{log.timestamp} | {log.action_type} | {log.actor}")
            print(f"  Target: {log.target}")
            print(f"  Error: {log.error_message}")
            print()


def main():
    """Main entry point"""
    import argparse
    
    parser = argparse.ArgumentParser(description='Audit Logging System')
    parser.add_argument('vault_path', type=str, help='Path to Obsidian vault')
    parser.add_argument('--view', action='store_true', help='View todays audit')
    parser.add_argument('--search', type=str, help='Search logs')
    parser.add_argument('--errors', action='store_true', help='View errors')
    parser.add_argument('--export', action='store_true', help='Export logs')
    parser.add_argument('--start', type=str, help='Export start date')
    parser.add_argument('--end', type=str, help='Export end date')
    parser.add_argument('--format', type=str, default='json', help='Export format')
    parser.add_argument('--log', type=str, help='Log a test action')
    
    args = parser.parse_args()
    
    vault_path = Path(args.vault_path)
    
    if not vault_path.exists():
        logger.error(f"Vault path does not exist: {vault_path}")
        sys.exit(1)
    
    if args.log:
        # Log a test action
        logger = AuditLogger(str(vault_path))
        log_id = logger.log(
            action_type=ActionType.TASK_CREATE,
            actor='test_user',
            target='test_task',
            parameters={'test': 'data'},
            result='success'
        )
        print(f"✅ Test log entry created: {log_id}")
        return
    
    viewer = AuditViewer(str(vault_path))
    
    if args.view:
        viewer.view_today()
        return
    
    if args.search:
        viewer.search(args.search)
        return
    
    if args.errors:
        viewer.view_errors()
        return
    
    if args.export:
        if not args.start or not args.end:
            print("Error: --start and --end required for export")
            return
        
        output = viewer.logger.export_logs(args.start, args.end, args.format)
        print(f"✅ Logs exported to: {output}")
        return
    
    # Default: show today's summary
    viewer.view_today()


if __name__ == '__main__':
    main()
